name: Check Pull Request

on:
  # Triggers the workflow on pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on:  windows-latest
    steps:
      - name: Checkout Repository and Sub-Modules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Install mingw 
        run: sudo apt-get install gcc-mingw-w64
        
      - name: configure cmake
        run: |
          cmake --version
          cmake -S . -B build -G "MinGW Makefiles"

      - name: Build Unit Tests
        run: |
          mkdir build
          cmake --build build

      - name: Execute Unit Tests
        run: |
          ctest --test-dir build
